---
- name: Install zabbix-agent-lvm-thin on Centos 8
  hosts: all
  become: yes
  vars:
    allow_world_readable_tmpfiles: true
    zabbix_server: 37.1.201.16
 
  tasks:

  - name: Install zabbix rhel 8 repo
    ansible.builtin.yum:
      name: http://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm
      state: present

  - name: Use dns to select version  of nodejs
    command: dnf module enable nodejs:16 -y

  - name: Install a list of packages
    ansible.builtin.yum:
      name:
        - zabbix-agent, sudo, lvm2
      state: present


  - name: Template a file to /etc/zabbix/zabbix_agentd.d/pool.lvm.conf
    template:
      src: zabbix/pool.lvm.conf.j2
      dest: /etc/zabbix/zabbix_agentd.d/pool.lvm.conf
      owner: root
      group: root
      mode: '0644'

  - name: Template a file to /etc/sudoers.d/zabbix-lvm
    template:
      src: zabbix/zabbix-lvm.j2
      dest: /etc/sudoers.d/zabbix-lvm
      owner: root
      group: root
      mode: '0600'

  - name: Template a file to /etc/zabbix/zabbix_agentd.conf 
    template:
      src: zabbix/zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: root
      mode: '0644'

  - name: Enable and start service zabbix-agent
    ansible.builtin.systemd:
      name: zabbix-agent
      state: started
      enabled: yes

...
